version: '3.8'

services:
  mysql:
    container_name: mysql_laravel
    image: mysql:8.0
    volumes:
      - './mysql_data/8.0:/var/lib/mysql'
      - './config/mysql:/etc/mysql/conf.d'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    networks:
      - laravel_network

  apache:
    container_name: apache_laravel
    image: ubuntu/apache2:latest
    volumes:
      - '/Users/macbookpro/Learn/htdocs:/var/www/html'
      - './logs:/usr/local/log'
      - './config/php/php.ini:/usr/local/etc/php/conf.d/php-config.ini'
      - './config/apache/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf'
    ports:
      - 80:80
    networks:
      - laravel_network
networks:
  laravel_network :
    name: laravel_network